<?php
/**
 * POST /api/admin/categories/create   (JSON, X-CSRF-Token)
 *
 *   {"label": "Porträtt"}   2–40 characters after trimming
 *
 * The key is generated by the server (see CategoryAdmin), never sent.
 *
 * 201 {category: {id, key, label, created_at}}
 * 400 invalid_request  401 not_authenticated  403 csrf_failed / forbidden_origin
 * 409 category_exists / reserved_category       413 request_too_large
 */

declare(strict_types=1);

use PixelMani\App;
use PixelMani\CategoryAdmin;
use PixelMani\Http;
use PixelMani\Input;
use PixelMani\JsonResponse;

$app = require __DIR__ . '/../../../../bootstrap.php';

$app->run(function (App $app): void {
    Http::requireMethod('POST');
    Http::query();
    $app->adminAuth()->requireAdminMutation();

    $body = Http::jsonBody(2048);
    Input::fields($body, ['label']);

    $category = (new CategoryAdmin($app->db->pdo(), $app->logger))->create($body['label']);

    JsonResponse::success(['category' => $category], 201);
});
