-- PixelMani database schema (MySQL 8.4 / MariaDB 10.6+ compatible subset).
--
-- Run against an EMPTY database. Tables are created without IF NOT EXISTS on
-- purpose: re-running this file against an existing database fails loudly
-- instead of silently keeping a table whose definition may differ.
--
-- Portability notes:
--  * Every table and every text column states its charset and collation
--    explicitly. MySQL 8's default (utf8mb4_0900_ai_ci) does not exist on
--    most MariaDB versions, so nothing here relies on server defaults.
--  * Identifiers, keys and paths use utf8mb4_bin / ascii_bin: exact byte
--    comparison, so 'a' <> 'å' and 'Foto' <> 'foto'.
--  * Category labels use utf8mb4_swedish_ci so ORDER BY label follows the
--    Swedish alphabet (Å, Ä, Ö after Z). Available on both servers.
--  * Other human-readable text uses utf8mb4_unicode_ci, available on both.
--  * Timestamps are DATETIME(6) holding UTC, written by the application.
--    Microseconds are kept because photos uploaded in one batch differ only
--    by fractions of a second, and the gallery is ordered by created_at.
--  * UUIDs are generated by the application, never by the database.
--  * `key` is a reserved word in MySQL/MariaDB and must always be quoted
--    with backticks.

SET NAMES utf8mb4;

CREATE TABLE categories (
  id         CHAR(36)     CHARACTER SET ascii   COLLATE ascii_bin          NOT NULL,
  `key`      VARCHAR(64)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL,
  label      VARCHAR(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_swedish_ci NOT NULL,
  created_at DATETIME(6)                                                   NOT NULL,

  PRIMARY KEY (id),
  -- Every lookup, the photos foreign key and category deletion go by key.
  UNIQUE KEY uq_categories_key (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE photos (
  id           CHAR(36)     CHARACTER SET ascii   COLLATE ascii_bin          NOT NULL,
  name         VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  storage_path VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL,
  category     VARCHAR(64)  CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NOT NULL,
  title        VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  location     VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL,
  `date`       DATE                                                          NULL,
  created_at   DATETIME(6)                                                   NOT NULL,
  -- Present in the current data model but not used by the application.
  is_hero      TINYINT(1)                                                    NOT NULL DEFAULT 0,

  -- Filled in by later phases (thumbnail backfill / new uploads).
  thumb_path   VARCHAR(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin        NULL,
  width        INT UNSIGNED                                                  NULL,
  height       INT UNSIGNED                                                  NULL,
  bytes        BIGINT UNSIGNED                                               NULL,
  mime         VARCHAR(100) CHARACTER SET ascii   COLLATE ascii_general_ci   NULL,

  PRIMARY KEY (id),
  -- Each stored file belongs to exactly one photo; deleting a photo deletes
  -- its file, so two rows sharing a path would lose an image.
  UNIQUE KEY uq_photos_storage_path (storage_path),
  -- Gallery, latest photos and the sitemap all ORDER BY created_at DESC.
  KEY idx_photos_created_at (created_at),
  -- Backs the foreign key and the "move photos out of a deleted category" update.
  KEY idx_photos_category (category),

  -- A photo must always point at an existing category. RESTRICT on both
  -- actions: a category with photos cannot be deleted (the application moves
  -- them to 'okategoriserad' first) and a key is never rewritten implicitly.
  CONSTRAINT fk_photos_category
    FOREIGN KEY (category) REFERENCES categories (`key`)
    ON UPDATE RESTRICT
    ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE site_settings (
  `key`      VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  value      TEXT        CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL,
  updated_at DATETIME(6)                                          NULL,

  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
